"""Added rating_average to Movie and favorite_genres to User

Revision ID: ad68b951fdc2
Revises: c40fd88f0a45
Create Date: 2024-10-20 14:03:05.837295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad68b951fdc2'
down_revision = 'c40fd88f0a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_average', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('rating_average')

    # ### end Alembic commands ###
