"""Add image_url column to movies table

Revision ID: c40fd88f0a45
Revises: c5cb47359fa1
Create Date: 2024-10-19 20:40:56.182173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40fd88f0a45'
down_revision = 'c5cb47359fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
